In [1]:
def f(x):
    return(x**2 + 2 * x + 1)

In [2]:
def g(x):
    return f(x) // 1

In [3]:
def S(x):
    hexagon = 3 * 3**0.5 * x**2 / 2
    pentagon = 5**0.5 * (5 + 2 * 5**0.5)**0.5 * x**2 / 4
    return 20 * hexagon + 12 * pentagon

def S_ceil(x):
    return int(S(x) + 1)

In [5]:
from scipy.optimize import golden


def f(x):
    return((x + 2)**2 - 3)


def g(x):
    return(abs(f(x)))


min_f = golden(f)
min_g = golden(g)

print(min_f, min_g)

-2.0 -0.2679491917808566


In [6]:
a, b = 3, 4
golden(g)

-0.2679491917808566

In [7]:
from scipy.optimize import golden


def f(x):
    return((x + a)**2 - b)


def g(x):
    return(abs(f(x)))


min_f = golden(f, brack=(-10, -4))
min_g = golden(g, brack=(-10, -4))

print(f(min_f), g(min_g))

-4.0 1.0706354913736504e-08


### Спектральное разложение

In [8]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [9]:
A = np.array([[1., 2., -1.],
             [2., 2., 5.],
             [-1., 5., -3.]])
A

array([[ 1.,  2., -1.],
       [ 2.,  2.,  5.],
       [-1.,  5., -3.]])

In [10]:
v, w = np.linalg.eigh(A)

In [11]:
v

array([-6.58,  1.15,  5.43])

In [12]:
w

array([[-0.25,  0.93, -0.27],
       [ 0.53, -0.11, -0.84],
       [-0.81, -0.35, -0.47]])

In [14]:
D = np.diag(v)
D

array([[-6.58,  0.  ,  0.  ],
       [ 0.  ,  1.15,  0.  ],
       [ 0.  ,  0.  ,  5.43]])

In [15]:
S = w.T

In [16]:
S.T @ S

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
S.T @ D @ S

array([[ 1.,  2., -1.],
       [ 2.,  2.,  5.],
       [-1.,  5., -3.]])

In [18]:
print('D=\n', D)
print('S=\n', S)

D=
 [[-6.58  0.    0.  ]
 [ 0.    1.15  0.  ]
 [ 0.    0.    5.43]]
S=
 [[-0.25  0.53 -0.81]
 [ 0.93 -0.11 -0.35]
 [-0.27 -0.84 -0.47]]
