## Линейная независимость векторов

In [1]:
import numpy as np

In [2]:
e1 = np.array([1., 0., 0.])
e2 = np.array([0., 5., 0.])
-3 * e1 + 2 * e2

array([-3., 10.,  0.])

In [3]:
a = np.array([-3., 10., 0.])

In [4]:
3 * e1 - 2 * e2 + 1* a

array([0., 0., 0.])

In [5]:
a == -3 * e1 + 2 * e2

array([ True,  True,  True])

In [6]:
M = np.array([e1, e2, a])
M

array([[ 1.,  0.,  0.],
       [ 0.,  5.,  0.],
       [-3., 10.,  0.]])

In [7]:
np.linalg.matrix_rank(M)

2

In [8]:
b1, b2, b3 = M[:, 0], M[:, 1], M[:, 2]
0 * b1 + 0 * b2 + b3

array([0., 0., 0.])

In [9]:
M = np.array([
    #a, b, c, d, e, f
    [0, 0, 1, 1, 1, 0],
    [1, 0, 1, 1, 0, 0],
    [1, 1, 0, 0, 1, 0],
    [1, 0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1, 1],
    [0, 1, 1, 1, 0, 0]
])

for a, b, c, d, e, f in M:
    N = np.array([
        [a, 0, 0],
        [b, d, 0],
        [c, e, f]
    ])
    print(N)
    print(np.linalg.matrix_rank(N))
    print(a, b, c, d, e, f)
    print()


[[0 0 0]
 [0 1 0]
 [1 1 0]]
2
0 0 1 1 1 0

[[1 0 0]
 [0 1 0]
 [1 0 0]]
2
1 0 1 1 0 0

[[1 0 0]
 [1 0 0]
 [0 1 0]]
2
1 1 0 0 1 0

[[1 0 0]
 [0 1 0]
 [0 0 1]]
3
1 0 0 1 0 1

[[0 0 0]
 [0 0 0]
 [1 1 1]]
1
0 0 1 0 1 1

[[0 0 0]
 [1 1 0]
 [1 0 0]]
2
0 1 1 1 0 0



In [10]:
M = np.array([
    [1, -1, 0, 0],
    [1, 0, -1, 0],
    [1, 0, 0, -1],
    [0, 1, -1, 0],
    [0, 1, 0, -1],
    [0, 0, 1, -1]
])
np.linalg.matrix_rank(M)

3

In [11]:
MM = np.array([
    [
        (1, 2, 2),
        (-1, 2, 1),
        (0, 8, 0)
    ],
    [
        (1, 2, 2),
        (-1, 2, 1),
        (0, 8, 6)
    ]
])
MM[0]

array([[ 1,  2,  2],
       [-1,  2,  1],
       [ 0,  8,  0]])

In [12]:
for M in MM:
    print(np.linalg.matrix_rank(M))

3
2
